trigger:
    -main

pool:
    vmImage: ubuntu-latest

variables:
    buildConfiguration: 'Relase'

steps:
    - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'